// FILE: app/src/main/java/com/sandeep/ganitabigyan/GameViewModel.kt
// VERSION: FINAL - Fixes the "Unresolved reference 'showFeedbackMessage'" error.

package com.sandeep.ganitabigyan

import android.content.Context
import android.os.Build
import android.os.Environment
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sandeep.ganitabigyan.utils.toLocaleNumerals
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.abs
import kotlin.random.Random

// Data classes and enums are unchanged
data class GameState(val questions: List<Question> = emptyList(), val currentQuestionIndex: Int = 0, val score: Int = 0, val wrongAttempts: Int = 0, val correctStreak: Int = 0, val selectedTypeKey: String = "game_type_mixed", val selectedLevelKey: String = "difficulty_easy", val selectedTypeDisplay: String = "", val selectedLevelDisplay: String = "", val isAutoScrollEnabled: Boolean = false, val isTimedChallenge: Boolean = false, val challengeJustFinished: Boolean = false, val timerValue: Long = 0L, val feedbackMessage: String? = null, val isLoading: Boolean = true)
data class Question(val questionText: String, val options: List<String>, val correctAnswer: String, val solution: String? = null, val userAnswer: String? = null, val isAnswered: Boolean = false)
enum class HapticFeedbackType { INCORRECT }
sealed class SoundEvent { object CorrectAnswer : SoundEvent() }
sealed class UiEvent { object ShowTimedChallengeDialog : UiEvent(); object RequestAutoScroll : UiEvent() }

class GameViewModel(private val context: Context) : ViewModel() {
    private val _gameState = MutableStateFlow(GameState())
    val gameState = _gameState.asStateFlow()
    private val _hapticEvent = MutableSharedFlow<HapticFeedbackType>()
    val hapticEvent = _hapticEvent.asSharedFlow()
    private val _uiEvent = MutableSharedFlow<UiEvent>()
    val uiEvent = _uiEvent.asSharedFlow()
    private val _soundEvent = MutableSharedFlow<SoundEvent>()
    val soundEvent = _soundEvent.asSharedFlow()
    private val settingsDataStore = SettingsDataStore(context)
    private var feedbackJob: Job? = null
    private var timerJob: Job? = null
    private var lifetimeScore = Pair(0, 0)

    init {
        loadSettingsAndStart()
        loadLifetimeScore()
    }
    fun resetGame() { loadSettingsAndStart() }
    fun refreshDisplayNames() { _gameState.update { it.copy(selectedTypeDisplay = getDisplayNameForKey(it.selectedTypeKey), selectedLevelDisplay = getDisplayNameForKey(it.selectedLevelKey)) } }
    private fun loadLifetimeScore() { viewModelScope.launch { try { val file = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "GanitaBigyan/lifetime_score.gba"); if (file.exists()) { val parts = file.readText().split(","); if (parts.size == 2) { lifetimeScore = Pair(parts[0].toIntOrNull() ?: 0, parts[1].toIntOrNull() ?: 0) } } } catch (e: Exception) { e.printStackTrace() } } }
    private fun saveLifetimeScore() { viewModelScope.launch { try { val documentsDir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS); val ganitaBigyanDir = File(documentsDir, "GanitaBigyan"); if (!ganitaBigyanDir.exists()) ganitaBigyanDir.mkdirs(); val file = File(ganitaBigyanDir, "lifetime_score.gba"); file.writeText("${lifetimeScore.first},${lifetimeScore.second}") } catch (e: Exception) { e.printStackTrace() } } }
    private fun loadSettingsAndStart() { viewModelScope.launch { _gameState.update { it.copy(isLoading = true) }; val savedTypeKey = settingsDataStore.gameType.first(); val savedLevelKey = settingsDataStore.difficultyLevel.first(); val newQuestions = List(50) { generateQuestion(savedTypeKey, savedLevelKey) }; _gameState.update { it.copy(selectedTypeKey = savedTypeKey, selectedLevelKey = savedLevelKey, selectedTypeDisplay = getDisplayNameForKey(savedTypeKey), selectedLevelDisplay = getDisplayNameForKey(savedLevelKey), isAutoScrollEnabled = settingsDataStore.autoScroll.first(), questions = newQuestions, currentQuestionIndex = 0, score = 0, wrongAttempts = 0, correctStreak = 0, isLoading = false) } } }
    fun updateSettings(newTypeKey: String, newLevelKey: String) { viewModelScope.launch { val isExtraHardAvailable = newTypeKey in listOf("game_type_mixed", "game_type_find_equation"); val finalLevelKey = if (!isExtraHardAvailable && newLevelKey == "difficulty_very_hard") "difficulty_hard" else newLevelKey; val newQuestions = List(50) { generateQuestion(newTypeKey, finalLevelKey) }; _gameState.update { it.copy(selectedTypeKey = newTypeKey, selectedLevelKey = finalLevelKey, selectedTypeDisplay = getDisplayNameForKey(newTypeKey), selectedLevelDisplay = getDisplayNameForKey(finalLevelKey), questions = newQuestions, currentQuestionIndex = 0, feedbackMessage = null, score = 0, wrongAttempts = 0, correctStreak = 0) }; settingsDataStore.saveSettings(newTypeKey, finalLevelKey) } }
    private fun appendQuestions(count: Int = 20) { val currentState = _gameState.value; val newQuestions = List(count) { generateQuestion(currentState.selectedTypeKey, currentState.selectedLevelKey) }; _gameState.update { it.copy(questions = it.questions + newQuestions) } }
    fun onAnswerSelected(answer: String) { val currentState = _gameState.value; val questionIndex = currentState.currentQuestionIndex; if (currentState.questions.getOrNull(questionIndex)?.isAnswered == true) return; val currentQuestion = currentState.questions[questionIndex]; val isCorrect = answer == currentQuestion.correctAnswer; val updatedQuestions = currentState.questions.toMutableList(); updatedQuestions[questionIndex] = currentQuestion.copy(userAnswer = answer, isAnswered = true); val newStreak = if (isCorrect) currentState.correctStreak + 1 else 0; val newScore = if (isCorrect) currentState.score + 1 else currentState.score; val newWrongAttempts = if (!isCorrect) currentState.wrongAttempts + 1 else currentState.wrongAttempts; val feedbackMessage = if (isCorrect) { if (newStreak >= 3) context.getString(R.string.feedback_streak, newStreak.toLocaleNumerals(context)) else context.getString(R.string.feedback_correct) } else context.getString(R.string.feedback_incorrect, currentQuestion.correctAnswer.toLocaleNumerals(context)); if (isCorrect) { lifetimeScore = lifetimeScore.copy(first = lifetimeScore.first + 1); viewModelScope.launch { if (settingsDataStore.isSoundEnabled.first()) { _soundEvent.emit(SoundEvent.CorrectAnswer) } } } else { lifetimeScore = lifetimeScore.copy(second = lifetimeScore.second + 1) }; saveLifetimeScore(); _gameState.update { it.copy(questions = updatedQuestions, score = newScore, wrongAttempts = newWrongAttempts, correctStreak = newStreak) }; showFeedbackMessage(feedbackMessage); viewModelScope.launch { if (!isCorrect) _hapticEvent.emit(HapticFeedbackType.INCORRECT); saveAnswerToFile(currentQuestion, answer, isCorrect); if (_gameState.value.isAutoScrollEnabled || _gameState.value.isTimedChallenge) { delay(1500); _uiEvent.emit(UiEvent.RequestAutoScroll) } } }

    // <<< THIS IS THE FIX: The function is added back in >>>
    private fun showFeedbackMessage(message: String) {
        feedbackJob?.cancel()
        feedbackJob = viewModelScope.launch {
            _gameState.update { it.copy(feedbackMessage = message) }
            delay(2500)
            _gameState.update { it.copy(feedbackMessage = null) }
        }
    }

    fun updateCurrentQuestionIndex(newIndex: Int) { val currentState = _gameState.value; val oldIndex = currentState.currentQuestionIndex; if (newIndex <= oldIndex) { if (newIndex >= currentState.questions.size - 5) { appendQuestions() }; _gameState.update { it.copy(currentQuestionIndex = newIndex) }; return }; val updatedQuestions = currentState.questions.toMutableList(); var skippedCount = 0; for (i in oldIndex until newIndex) { if (!updatedQuestions[i].isAnswered) { updatedQuestions[i] = updatedQuestions[i].copy(isAnswered = true, userAnswer = context.getString(R.string.qna_log_skipped)); skippedCount++ } }; if (skippedCount > 0) { lifetimeScore = lifetimeScore.copy(second = lifetimeScore.second + skippedCount); saveLifetimeScore(); showFeedbackMessage(context.getString(R.string.feedback_skipped, skippedCount.toLocaleNumerals(context))) }; _gameState.update { it.copy(questions = updatedQuestions, wrongAttempts = it.wrongAttempts + skippedCount, currentQuestionIndex = newIndex) }; if (newIndex >= currentState.questions.size - 5) { appendQuestions() } }
    fun toggleAutoScroll(isEnabled: Boolean) { viewModelScope.launch { settingsDataStore.saveAutoScroll(isEnabled); _gameState.update { it.copy(isAutoScrollEnabled = isEnabled) } } }
    fun startTimedChallenge(minutes: Int, typeKey: String, levelKey: String) { timerJob?.cancel(); val durationMillis = minutes * 60 * 1000L; updateSettings(typeKey, levelKey); _gameState.update { it.copy(isTimedChallenge = true, timerValue = durationMillis, challengeJustFinished = false) }; timerJob = viewModelScope.launch { var timeLeft = durationMillis; while (timeLeft > 0 && _gameState.value.isTimedChallenge) { delay(1000); timeLeft -= 1000; _gameState.update { it.copy(timerValue = timeLeft) } }; if (_gameState.value.isTimedChallenge) { _gameState.update { it.copy(isTimedChallenge = false, challengeJustFinished = true) } } } }
    fun stopTimedChallenge() { timerJob?.cancel(); _gameState.update { it.copy(isTimedChallenge = false, timerValue = 0, challengeJustFinished = false) }; updateSettings(_gameState.value.selectedTypeKey, _gameState.value.selectedLevelKey) }
    fun dismissChallengeSummary() { _gameState.update { it.copy(challengeJustFinished = false) }; updateSettings(_gameState.value.selectedTypeKey, _gameState.value.selectedLevelKey) }
    fun requestTimedChallengeDialog() { viewModelScope.launch { _uiEvent.emit(UiEvent.ShowTimedChallengeDialog) } }
    fun triggerHapticFeedback(type: HapticFeedbackType) { viewModelScope.launch { if (!settingsDataStore.isVibrationEnabled.first()) return@launch; val vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) { (context.getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager).defaultVibrator } else { @Suppress("DEPRECATION") context.getSystemService(Context.VIBRATOR_SERVICE) as Vibrator }; if (vibrator.hasVibrator()) { VibrationEffect.createWaveform(longArrayOf(0, 75, 50, 75), -1)?.let { vibrator.vibrate(it) } } } }
    private fun saveAnswerToFile(question: Question, userAnswer: String, isCorrect: Boolean) { viewModelScope.launch { try { val keyQuestion = context.getString(R.string.qna_log_question_key); val keyYourAnswer = context.getString(R.string.qna_log_your_answer_key); val keyCorrectAnswer = context.getString(R.string.qna_log_correct_answer_key); val keyResult = context.getString(R.string.qna_log_result_key); val resultIdentifier = if (isCorrect) { context.getString(R.string.qna_log_result_correct_id) } else { context.getString(R.string.qna_log_result_incorrect_id) }; val documentsDir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS); val ganitaBigyanDir = File(documentsDir, "GanitaBigyan"); if (!ganitaBigyanDir.exists()) ganitaBigyanDir.mkdirs(); val file = File(ganitaBigyanDir, "qna.gba"); val timestamp = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ENGLISH).format(Date()); val contentToAppend = "[$timestamp]\n$keyQuestion: ${question.questionText}\n$keyYourAnswer: $userAnswer\n$keyCorrectAnswer: ${question.correctAnswer}\n$keyResult: $resultIdentifier\n\n"; file.appendText(contentToAppend) } catch (e: Exception) { e.printStackTrace() } } }
    private fun generateQuestion(typeKey: String, levelKey: String): Question { val actualTypeKey = if (typeKey == "game_type_mixed") { listOf("game_type_addition", "game_type_subtraction", "game_type_multiplication", "game_type_division").random() } else { typeKey }; return when (actualTypeKey) { "game_type_addition" -> generateAddition(levelKey); "game_type_subtraction" -> generateSubtraction(levelKey); "game_type_multiplication" -> generateMultiplication(levelKey); "game_type_division" -> generateDivision(levelKey); "game_type_find_equation" -> generateFindExpression(levelKey); else -> generateAddition(levelKey) } }
    private fun generateAddition(levelKey: String): Question { val (n1, n2) = when (levelKey) { "difficulty_easy" -> Random.nextInt(1, 10) to Random.nextInt(1, 10); "difficulty_medium" -> Random.nextInt(10, 100) to Random.nextInt(10, 100); "difficulty_hard" -> Random.nextInt(100, 1000) to Random.nextInt(100, 1000); "difficulty_very_hard" -> Random.nextInt(1000, 10000) to Random.nextInt(1000, 10000); else -> Random.nextInt(1, 10) to Random.nextInt(1, 10) }; val answer = n1 + n2; val options = generateOptions(answer); val questionText = "$n1 + $n2 = ?"; val solutionText = "$n1 + $n2 = $answer"; return Question(questionText, options.map { it.toString() }, answer.toString(), solution = solutionText) }
    private fun generateSubtraction(levelKey: String): Question { val (n1, n2) = when (levelKey) { "difficulty_easy" -> Random.nextInt(5, 20) to Random.nextInt(1, 5); "difficulty_medium" -> Random.nextInt(20, 100) to Random.nextInt(10, 20); "difficulty_hard" -> Random.nextInt(100, 1000) to Random.nextInt(10, 100); "difficulty_very_hard" -> Random.nextInt(100, 1000) to Random.nextInt(10, 100); else -> Random.nextInt(5, 20) to Random.nextInt(1, 5) }.let { (a, b) -> if (a > b) a to b else b to a }; val answer = n1 - n2; val options = generateOptions(answer); val questionText = "$n1 - $n2 = ?"; val solutionText = "$n1 - $n2 = $answer"; return Question(questionText, options.map { it.toString() }, answer.toString(), solution = solutionText) }
    private fun generateMultiplication(levelKey: String): Question { val (n1, n2) = when (levelKey) { "difficulty_easy" -> Random.nextInt(2, 10) to Random.nextInt(2, 10); "difficulty_medium" -> Random.nextInt(10, 26) to Random.nextInt(2, 10); "difficulty_hard" -> Random.nextInt(11, 31) to Random.nextInt(11, 21); "difficulty_very_hard" -> Random.nextInt(11, 31) to Random.nextInt(11, 21); else -> Random.nextInt(2, 10) to Random.nextInt(2, 10) }; val answer = n1 * n2; val options = generateOptions(answer); val questionText = "$n1 × $n2 = ?"; val solutionText = "$n1 × $n2 = $answer"; return Question(questionText, options.map { it.toString() }, answer.toString(), solution = solutionText) }
    private fun generateDivision(levelKey: String): Question { val (ans, div) = when (levelKey) { "difficulty_easy" -> Random.nextInt(2, 11) to Random.nextInt(2, 6); "difficulty_medium" -> Random.nextInt(5, 21) to Random.nextInt(2, 11); "difficulty_hard" -> Random.nextInt(10, 51) to Random.nextInt(5, 21); "difficulty_very_hard" -> Random.nextInt(10, 51) to Random.nextInt(5, 21); else -> Random.nextInt(2, 11) to Random.nextInt(2, 6) }; val num = ans * div; val answer = ans; val options = generateOptions(answer); val questionText = "$num ÷ $div = ?"; val solutionText = "$num ÷ $div = $answer"; return Question(questionText, options.map { it.toString() }, answer.toString(), solution = solutionText) }
    private fun generateFindExpression(levelKey: String): Question { val answer = when (levelKey) { "difficulty_easy" -> Random.nextInt(5, 21); "difficulty_medium" -> Random.nextInt(20, 101); "difficulty_hard" -> Random.nextInt(50, 201); "difficulty_very_hard" -> Random.nextInt(100, 501); else -> Random.nextInt(5, 21) }; val correctExpr = generateExpression(answer, levelKey).first; val wrongExpr1 = generateExpression(answer + (Random.nextInt(-20, 20).takeIf { it != 0 } ?: 1), levelKey).first; val wrongExpr2 = generateExpression(answer + (Random.nextInt(-20, 20).takeIf { it != 0 } ?: 2), levelKey).first; val wrongExpr3 = generateExpression(answer + (Random.nextInt(-20, 20).takeIf { it != 0 } ?: 3), levelKey).first; val options = listOf(correctExpr, wrongExpr1, wrongExpr2, wrongExpr3).shuffled(); val questionText = context.getString(R.string.question_find_correct_equation, answer.toString()); return Question(questionText, options, correctExpr) }
    private fun generateExpression(target: Int, levelKey: String): Pair<String, Int> { val safeTarget = if (target <= 1) Random.nextInt(2, 20) else target; while (true) { try { return when (levelKey) { "difficulty_easy" -> if (Random.nextBoolean()) { val n1 = Random.nextInt(1, safeTarget); "$n1 + ${safeTarget - n1}" to safeTarget } else { val n2 = Random.nextInt(1, 20); "${safeTarget + n2} - $n2" to safeTarget }; "difficulty_medium" -> if (Random.nextBoolean()) { val factors = findFactors(safeTarget).filter { it > 1 && it != safeTarget }; val n1 = if (factors.isNotEmpty()) factors.random() else 2; if (safeTarget % n1 == 0) "$n1 × ${safeTarget / n1}" to safeTarget else generateExpression(safeTarget, levelKey) } else { val n2 = Random.nextInt(2, 11); "${safeTarget * n2} ÷ $n2" to safeTarget }; else -> { if (Random.nextBoolean()) { val factors = findFactors(safeTarget).filter { it > 1 }; if (factors.isNotEmpty()) { val c = factors.random(); val abSum = safeTarget / c; if (abSum * c == safeTarget && abSum > 2) { val a = Random.nextInt(1, abSum); val b = abSum - a; return "($a + $b) × $c" to safeTarget } } }; val n2 = Random.nextInt(2, 11); return "${safeTarget * n2} ÷ $n2" to safeTarget } } } catch (e: Exception) { /* retry loop */ } } }
    private fun findFactors(number: Int): List<Int> = (1..abs(number)).filter { number % it == 0 }
    private fun generateOptions(answer: Int, count: Int = 4): List<Int> { val options = mutableSetOf(answer); val range = maxOf(1, answer / 10); while (options.size < count) { val offset = (Random.nextInt(-range - 2, range + 3).takeIf { it != 0 } ?: 1); val wrong = answer + offset; if (wrong >= 0) { options.add(wrong) } }; return options.toList().shuffled() }
    private fun getDisplayNameForKey(key: String): String { val resourceId = context.resources.getIdentifier(key, "string", context.packageName); return if (resourceId != 0) context.getString(resourceId) else key }
}